### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by smordarski** [Mordarski-Networks/Mordarski-Networks-assets#38]
## Task list

This is a task list for tracking progress on our code.

### generate_filter.py

- [ ] Look into making command line switches.
- [ ] Look into making a GUI.
- [ ] Create classes to make our module reusable.
